### ISSUE TITLE
TypeError: You provided 'function (source) { ... }' where a stream was expected.

### ISSUE THREAD

**Issue by huan** [wechaty/ha-wechaty#4]
> TypeError: You provided 'function (source) { return source.lift.call(merge_1.merge.apply(void 0, [source].concat(observables))); }' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

There's something wrong with the Reset Epic.

To be fixed.

```sh
TypeError: You provided 'function (source) { return source.lift.call(merge_1.merge.apply(void 0, [source].concat(observables))); }' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/util/subscribeTo.ts:27:11)
    at Object.subscribeToResult (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/util/subscribeToResult.ts:36:10)
    at SwitchMapSubscriber._innerSub (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/operators/switchMap.ts:139:30)
    at SwitchMapSubscriber._next (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/operators/switchMap.ts:128:10)
    at SwitchMapSubscriber.Subscriber.next (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at DebounceSubscriber.Subscriber._next (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/Subscriber.ts:139:22)
    at DebounceSubscriber.emitValue (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/operators/debounce.ts:145:18)
    at DebounceSubscriber.notifyNext (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/operators/debounce.ts:122:10)
    at InnerSubscriber._next (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
    at InnerSubscriber.Subscriber.next (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at AsyncAction.dispatch (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/observable/interval.ts:75:14)
    at AsyncAction._execute (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:122:12)
    at AsyncAction.execute (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:97:24)
    at AsyncScheduler.flush (/Users/huan/chatie/ha-wechaty/node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:58:26)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by huan** [comment]
It turns out that there are two `merge` in `rxjs`:

```ts
import { merge } from 'rxjs'
```

and

```ts
import {merge } from 'rxjs/operators'
```

This problem was caused by the following code:

```ts
import { merge } from 'rxjs/operators'

action$.pipe(
  mergeMap(action => merge(...))
)
```

The following diff fixed this problem:

```diff
- import { merge } from 'rxjs/operators'
+ import { merge } from 'rxjs'
```

P.S. the `merge` was auto-imported by vscode, which makes me take quite some time to figure it out...

**Comment by huan** [comment]
Fixed.

**Comment by bhootd** [comment]
Thank you for documenting the resolution. It helped me with a similar error, only the operator in my case was `zip` v/s `zipWith`. The latter caused the error; moving to `zip` fixed the problem.

**Comment by huan** [comment]
Yeah, for sure! Feels like an UX bug in RxJS—exporting the same name all over the place just adds to the dev confusion. And with them constantly shuffling export paths, it’s like a moving target. Devs shouldn’t have to play detective just to import the right thing!
